# Generated by Django 4.2 on 2024-05-05 11:07

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.AlterField(
            model_name="recruiter",
            name="company_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recruiter",
            name="company_website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
